### PR TITLE
Timestamp Changes

### PR DESCRIPTION
**Pull request by bogdanadrianmarc**
This PR addresses issue #20 . It changes timestamp format to include milliseconds and timezone, and renames field name from `timestamp` to `ts` in returning JSON

### CODE REVIEW

**Review by joescottdave — APPROVED** [review]
Lgtm

**Review by ijdickinson — APPROVED** [review]
lgtm

**Comment by andrew-pickin-epi** [comment]
I don't believe these changes match the requested format. for n=3
Implemented 
`%Y-%m-%d %H:%M:%S.%3N %Z`
requested
`%Y-%m-%dT%H:%M:%S.%3NZ`
Further, is the code assuming the time is GMT?

**Review by andrew-pickin-epi — CHANGES_REQUESTED** [review]
Requested format 
%Y-%m-%dT%H:%M:%S.%3NZ
which implies GMT

**Review by andrew-pickin-epi — COMMENTED** [review]
Is there an assumption here that the time will already be in UTC?
Are we content with that?

**Comment by ijdickinson** [comment]
@bogdanadrianmarc @andrew-pickin-epi  We can coerce a Ruby DateTime to UTC with the `.utc` method. So we could ensure that all timestamps are UTC by:

```ruby
def process_timestamp(timestamp)
  format_datetime(timestamp.utc)
end
```

I guess the question is: what should be the desired behaviour when a log message is emitted during BST?

**Review by ijdickinson — APPROVED** [review]
lgtm

**Pull request merged**
